@startuml helloWorld
' Define the main location (URL or local file path)
!define OCIPuml https://raw.githubusercontent.com/rUser75/OCI-icons-for-plantuml/v1.0/dist
' Include main OCICommon and then resource files
!include OCIPuml/OCICommon.puml
!include OCIPuml/Compute/all.puml

oci_VirtualMachine(one,VirtualMachine,this_is_the_pngImage)
' this is a sprite color,scale,alias
OCI_VIRTUALMACHINE(blue,1,virta)
' this is a sprite color,scale,alias,shape (rectangle, node,agent),label
OCI_FUNCTIONS(red,0.5,funct,node,virtualMachine)

funct --> virta
virta --> one

@enduml
